name: Build and Push
on: 
  push:
    branches:
      - latest
jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to Docker Registry
      run: >
        docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
    - name: Pull Latest
      run: >
        docker pull docker.pkg.github.com/${{ github.repository }}/code-server:latest
    - name: Build Docker Image
      run: >
        docker build --pull \
          --cache-from docker.pkg.github.com/${{ github.repository }}/code-server:latest \
          --build-arg vscodeVersion=${{ secrets.VSCODE_VERSION }} \
          --build-arg VCS_REF=${{ github.sha }} \
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
          -t code-server .
    - name: Push Docker Image
      run: >
        docker tag code-server docker.pkg.github.com/${{ github.repository }}/code-server:latest && \
        docker push docker.pkg.github.com/${{ github.repository }}/code-server:latest
    - name: Push Docker Image with Version
      run: >
        docker tag code-server docker.pkg.github.com/${{ github.repository }}/code-server:${{ secrets.VSCODE_VERSION }} && \
        docker push docker.pkg.github.com/${{ github.repository }}/code-server:${{ secrets.VSCODE_VERSION }}
